modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"
issueTrackerURL="https://github.com/bconlon1/Vanilla-Equals/issues"

[[mods]]
modId="vanilla_equals"
version="${file.jarVersion}"
displayName="Vanilla Equals"
updateJSONURL="https://github.com/bconlon1/Vanilla-Equals/updates.json"
displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="equals.png"
credits="NeoForge"
authors="bconlon"
displayTest="MATCH_VERSION"
description='''A mod with the goal of bridging the gaps between vanilla content through added depth.'''

[[dependencies.vanilla_equals]]
    modId="neoforge"
    type = "required"
    versionRange="[20.4.200,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vanilla_equals]]
    modId="minecraft"
    type = "required"
    versionRange="[1.20.4,1.20.5)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="vanilla_equals.mixins.json"
